### ISSUE TITLE
when creating the runtime for a language that use K3 aspect with dependency to other eclipse project, the depency is not copied to the runtime project

### ISSUE THREAD

**Issue by dvojtise** [diverse-project/melange#56]
when creating the runtime for a language that use K3 aspect with dependency to other eclipse project, the depency is not copied to the runtime project

**Comment by fcoulon** [comment]
Should be done with 006daba59d53f2edc2f712e306f9069c4ad84bdd

**Comment by dvojtise** [comment]
ok for me (tested with TFSM and SigPML concurrent on latest Studio )

**Comment by dvojtise** [comment]
I have a project (ActivityDiagram concurrent) that requires org.eclipse.xtext (in order to be able to load model using XtextResourceSet )
this dependency is not correctly copied

**Comment by fcoulon** [comment]
I am not able to reproduce. I need more details.

**Comment by dvojtise** [comment]
grab language from https://github.com/gemoc/activitydiagram/tree/master/dev/gemoc_concurrent/language_workbench

generate the runtime. 
This will remove the dependency to xtext that is required by ActivityAspect code in the generated xactivitydiagram plugin

**Comment by fcoulon** [comment]
Should be fixed by 064e5d83149709ba1dae213d136492cf1b9fbb1d

**Comment by dvojtise** [comment]
Still not working with GEMOC Studio 30-10-2016 (Melange 0.2.0.201610271456). step to reproduce bug 
- new example TFSM concurrent. 
- Delete the runtime model project
- generate all on the melange file

only xtext is copied, dependency to Groovy plugin is not copied

**Comment by fcoulon** [comment]
Sorry I missed my merge d9db94478f2eacebcdcd0accb5cb0dda1e003f57

Should be come back with 4a641dbbc8422188371e89cc15a37caf23b2ef20
